### PR TITLE
created the sign-up page

### PR DESCRIPTION
**Pull request by Godwindaniel10**

### CODE REVIEW

**Comment by tbm5k** [comment]
@Godwindaniel10 make the sign up form a react component and place it on the components directory

**Comment by Godwindaniel10** [comment]
@tbm5k i don't use react

**Comment by tbm5k** [comment]
Okay, I'll update the issue for the others. Good job though 💯

**Comment by Godwindaniel10** [comment]
@tbm5k Done. 

Thanks for the compliment .....

**Pull request merged**
